# To run netlify-cms locally:
#
# 1. Replace the `backend` config with the commented configuration below.
# 2. Remove the `src/` prefix from `file` and `folder` attributes to make them
#    relative to the site URL, not relative to the repo root (which is needed
#    by the `github` backend which uses the GitHub API endpoint to find files).
# 3. On the command line, run:
#        cd src && npx netlify-cms-proxy-server
#
# local_backend: true
# backend:
#   name: git-gateway
#
backend:
  name: github
  repo: dxw/terraform-code-playbook
  branch: main
  open_authoring: true
media_library:
  name: disabled
media_folder: _images
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: home
    label: Home
    label_singular: Home page
    files:
      - name: home
        label: Home page
        file: src/index.md
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: Body, name: body, widget: markdown, required: true }

  - name: redirects
    label: Redirects
    label_singular: Redirect manager
    files:
      - name: redirect-manager
        label: Redirect manager
        file: src/redirects.json
        fields:
          - label: Redirects
            name: redirects
            widget: "list"
            summary: '{{fields.from}} - {{fields.to}}'
            fields:
              - {label: Redirect from, name: from, widget: string, default: "/redirect-from"}
              - {label: Redirect to, name: to, widget: string, default: "/redirect-to"}
